import {
  documents,
  accounts,
  payments,
  more,
  cartaidentita,
  diary,
  calendar,
  focus,
  speedometer,
  avatarHeader,
  avatar,
  add,
  twitter,
  facebook,
  settings,
  sun,
  logout,
} from "./icons";
export const iconsList = [
  {
    documents: documents,
    accounts: accounts,
    payments: payments,
    more: more,
    cartaidentita: cartaidentita,
    diary: diary,
    calendar: calendar,
    focus: focus,
    speedometer: speedometer,
    avatar: avatar,
    avatarHeader: avatarHeader,
    add: add,
    twitter: twitter,
    facebook: facebook,
    settings: settings,
    sun: sun,
    logout: logout,
  },
];
